# tell netlify about your build script and output directory

[build]
  command = "npm run build-locale"
  publish = "dist"

# redirect to german, spanish or english landing pages

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force= true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/ukr"
  status = 302
  force = true
  conditions = {Language = ["ukr"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true
